# Generated by Django 6.0.6 on 2026-06-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name_sw', models.CharField(max_length=100, verbose_name='Jina la Zao (Kiswahili)')),
                ('crop_name_en', models.CharField(max_length=100, verbose_name='Jina la Zao (English)')),
                ('crop_group', models.CharField(choices=[('cereals', 'Nafaka / Cereals'), ('legumes', 'Mikunde / Legumes'), ('roots', 'Mizizi / Root Crops'), ('vegetables', 'Mboga / Vegetables'), ('fruits', 'Matunda / Fruits'), ('cash_crops', 'Mazao ya Biashara / Cash Crops')], max_length=50)),
                ('priority_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zao',
                'verbose_name_plural': 'Mazao',
                'ordering': ['priority_level', 'crop_name_sw'],
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=100, unique=True)),
                ('description_sw', models.TextField(help_text='Maelezo ya intent kwa Kiswahili')),
                ('required_entities', models.CharField(blank=True, help_text='e.g. crop, location', max_length=200)),
                ('follow_up_prompt', models.TextField(blank=True, help_text='Swali la kufuatia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intent',
                'verbose_name_plural': 'Intents',
                'ordering': ['intent_name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100, unique=True)),
                ('rain_pattern_simple', models.CharField(choices=[('chache', 'Mvua Chache'), ('wastani', 'Mvua za Wastani'), ('nyingi', 'Mvua Nyingi'), ('bimodal', 'Mvua Mbili kwa Mwaka')], max_length=50)),
                ('rainfall_band_mm', models.CharField(blank=True, help_text='e.g. 400-700mm', max_length=50)),
                ('altitude_band_m', models.CharField(blank=True, help_text='e.g. 0-1000m', max_length=50)),
                ('risk_factors', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['zone_name'],
            },
        ),
        migrations.CreateModel(
            name='FarmerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('keywords', models.TextField(help_text='Keywords separated by commas')),
                ('answer_reference', models.CharField(blank=True, max_length=200)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_questions', to='crops.crop')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_questions', to='crops.intent')),
            ],
            options={
                'verbose_name': 'Swali la Mkulima',
                'verbose_name_plural': 'Maswali ya Wakulima',
            },
        ),
        migrations.CreateModel(
            name='SeedVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(max_length=100)),
                ('maturity_class', models.CharField(blank=True, choices=[('early', 'Early (chini ya siku 90)'), ('medium', 'Medium (siku 90-120)'), ('late', 'Late (zaidi ya siku 120)')], max_length=20)),
                ('maturity_days_min', models.PositiveIntegerField(blank=True, null=True)),
                ('maturity_days_max', models.PositiveIntegerField(blank=True, null=True)),
                ('drought_tolerance', models.CharField(blank=True, help_text='High / Medium / Low', max_length=50)),
                ('disease_tolerance', models.CharField(blank=True, max_length=200)),
                ('rainfall_requirement_mm', models.CharField(blank=True, max_length=50)),
                ('altitude_requirement_m', models.CharField(blank=True, max_length=50)),
                ('seed_source', models.CharField(blank=True, help_text='e.g. SEEDCO, Pannar', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='crops.crop')),
                ('recommended_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_varieties', to='crops.zone')),
            ],
            options={
                'verbose_name': 'Aina ya Mbegu',
                'verbose_name_plural': 'Aina za Mbegu',
                'ordering': ['crop', 'variety_name'],
            },
        ),
        migrations.CreateModel(
            name='AnswerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_reference', models.CharField(max_length=200, unique=True)),
                ('answer_text_sw', models.TextField(verbose_name='Jibu (Kiswahili)')),
                ('follow_up_question', models.TextField(blank=True)),
                ('caution_note', models.TextField(blank=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_templates', to='crops.crop')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_templates', to='crops.intent')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_templates', to='crops.zone')),
            ],
            options={
                'verbose_name': 'Answer Template',
                'verbose_name_plural': 'Answer Templates',
                'ordering': ['intent', 'crop', 'zone'],
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_word', models.CharField(max_length=100)),
                ('variation', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('crop', 'Zao / Crop'), ('intent', 'Intent'), ('location', 'Eneo / Location'), ('input', 'Pembejeo / Input'), ('general', 'Jumla / General')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.crop')),
            ],
            options={
                'verbose_name': 'Synonym',
                'verbose_name_plural': 'Synonyms',
                'ordering': ['main_word'],
                'unique_together': {('main_word', 'variation')},
            },
        ),
        migrations.CreateModel(
            name='LocationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='crops.zone')),
            ],
            options={
                'verbose_name': 'Location Mapping',
                'verbose_name_plural': 'Location Mappings',
                'ordering': ['region_name', 'district_name'],
                'unique_together': {('region_name', 'district_name')},
            },
        ),
        migrations.CreateModel(
            name='CropProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_varieties', models.TextField(blank=True, help_text='Orodha ya mbegu zinazopendekezwa')),
                ('maturity_days_min', models.PositiveIntegerField(blank=True, null=True)),
                ('maturity_days_max', models.PositiveIntegerField(blank=True, null=True)),
                ('planting_window_simple', models.CharField(blank=True, help_text='e.g. Oktoba - Novemba', max_length=200)),
                ('spacing', models.CharField(blank=True, help_text='e.g. 75cm x 25cm', max_length=100)),
                ('planting_method', models.TextField(blank=True)),
                ('fertilizer_planting', models.TextField(blank=True, help_text='Mbolea ya kupandia')),
                ('fertilizer_top_dressing', models.TextField(blank=True, help_text='Mbolea ya juu')),
                ('common_pests', models.TextField(blank=True)),
                ('common_diseases', models.TextField(blank=True)),
                ('common_symptoms', models.TextField(blank=True)),
                ('harvest_window', models.CharField(blank=True, max_length=200)),
                ('storage_notes', models.TextField(blank=True)),
                ('market_notes', models.TextField(blank=True)),
                ('caution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='crops.crop')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_profiles', to='crops.zone')),
            ],
            options={
                'verbose_name': 'Crop Profile',
                'verbose_name_plural': 'Crop Profiles',
                'unique_together': {('crop', 'zone')},
            },
        ),
    ]
