# Generated by Django 4.2.16 on 2026-09-10 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='TZS')),
                ('paid_on', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('mixx', 'Mixx by Yas'), ('airtel', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('bank', 'Benki'), ('cash', 'Taslimu')], default='mpesa', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Namba ya muamala', max_length=80)),
                ('period_label', models.CharField(blank=True, help_text='Mfano: Oktoba 2026', max_length=60)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Malipo',
                'verbose_name_plural': 'Malipo',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='Kilimoni LABS', max_length=120)),
                ('plan_name', models.CharField(default='Huduma ya Mwezi', max_length=120)),
                ('monthly_fee', models.PositiveIntegerField(default=50000, help_text='TZS')),
                ('status', models.CharField(choices=[('trial', 'Ofa ya Uzinduzi'), ('active', 'Imelipwa'), ('pending', 'Inasubiri Malipo'), ('overdue', 'Imechelewa'), ('suspended', 'Imesitishwa')], default='trial', max_length=20)),
                ('period_start', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(help_text='Tarehe ya mwisho ya malipo ya kipindi hiki')),
                ('grace_days', models.PositiveIntegerField(default=7, help_text='Siku za neema baada ya tarehe ya malipo kupita')),
                ('service_active', models.BooleanField(default=True, help_text='Ikizimwa, bot itajibu ujumbe wa "huduma imesitishwa"')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Huduma (Subscription)',
                'verbose_name_plural': 'Huduma (Subscription)',
                'ordering': ['-updated_at'],
            },
        ),
    ]
