# Generated by Django 6.0.6 on 2026-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_user_last_crop_id_remove_user_last_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_crop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_intent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='session_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
