# Generated by Django 4.2.16 on 2026-08-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('preferred_language', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English')], default='sw', max_length=5)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('session_state', models.JSONField(blank=True, default=dict)),
                ('last_crop_id', models.IntegerField(blank=True, null=True)),
                ('last_intent', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Mkulima',
                'verbose_name_plural': 'Wakulima',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='UnresolvedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_message', models.TextField()),
                ('normalized_text', models.TextField(blank=True)),
                ('reason', models.CharField(choices=[('no_intent', 'Intent Haijatambuliwa'), ('no_crop', 'Zao Halijapatikana'), ('no_answer', 'Jibu Halijapatikana'), ('no_location', 'Eneo Halijatambuliwa'), ('other', 'Sababu Nyingine')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri Review'), ('resolved', 'Imeshughulikiwa'), ('ignored', 'Imepuuzwa')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('resolution_notes', models.TextField(blank=True)),
                ('detected_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.crop')),
                ('detected_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.intent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_queries', to='bot.user')),
            ],
            options={
                'verbose_name': 'Swali Lisiloshughulikiwa',
                'verbose_name_plural': 'Maswali Yasiyoshughulikiwa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_direction', models.CharField(choices=[('inbound', 'Kutoka kwa Mkulima'), ('outbound', 'Kutoka kwa Mfumo')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Maandishi'), ('audio', 'Sauti'), ('image', 'Picha'), ('document', 'Hati')], default='text', max_length=20)),
                ('raw_message', models.TextField()),
                ('normalized_text', models.TextField(blank=True)),
                ('detected_location', models.CharField(blank=True, max_length=100)),
                ('response_reference', models.CharField(blank=True, max_length=200)),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detected_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.crop')),
                ('detected_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.intent')),
                ('detected_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.zone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='bot.user')),
            ],
            options={
                'verbose_name': 'Mazungumzo',
                'verbose_name_plural': 'Mazungumzo',
                'ordering': ['-created_at'],
            },
        ),
    ]
