# Generated by Django 6.0.6 on 2026-06-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_crop_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_intent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_state',
        ),
    ]
