# Generated by Django 4.2.16 on 2026-08-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_user_phone_number'),
        ('bot', '0004_user_last_crop_id_user_last_intent_and_more'),
    ]

    operations = [
    ]
