# Generated by Django 4.2.16 on 2026-08-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_merge_20260813_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
