# Generated by Django 6.0.6 on 2026-06-25 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('content_manager', 'Content Manager'), ('agronomy_reviewer', 'Agronomy Reviewer'), ('data_manager', 'Data Manager'), ('viewer', 'Viewer')], default='viewer', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('success_flag', models.BooleanField(default=False)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.crop')),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.intent')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.zone')),
            ],
            options={
                'verbose_name': 'Analytics Log',
                'verbose_name_plural': 'Analytics Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('create', 'Imetengenezwa'), ('update', 'Imebadilishwa'), ('delete', 'Imefutwa'), ('import', 'Imeingizwa (Import)')], max_length=20)),
                ('change_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.adminuser')),
            ],
            options={
                'verbose_name': 'Content Update',
                'verbose_name_plural': 'Content Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
